name: Publish Packages

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: ossrh
          settings-path: ${{ github.workspace }}

      - name: Publish to Maven Central and Github Packages
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY : ${{ secrets.GPG_PRIVATE_KEY }}
          BOOTSOLANA_TOKEN: ${{ secrets.BOOTSOLANA_TOKEN }}
          BOOTSOLANA_USER: ${{ secrets.BOOTSOLANA_USER }}
        run: |
          ./gradlew publish --no-daemon --no-parallel --stacktrace

